In [1]:
import numpy as np

a1 = np.array([1, 2, 3])
a2 = np.array([[1, 2, 3]])
a3 = np.array([[1], [2], [3]])

print(a1)
print(a1.ndim, a1.shape)
print(a2)
print(a2.ndim, a2.shape)
print(a3)
print(a3.ndim, a3.shape)

[1 2 3]
(1, (3,))
[[1 2 3]]
(2, (1, 3))
[[1]
 [2]
 [3]]
(2, (3, 1))


In [3]:
m1 = np.matrix([1, 2, 3, 4])

print(m1)
print(m1.T)
print(m1 * m1.T)
print(m1.dot(m1.T))
print(np.multiply(m1, m1))

a1 = np.array([1, 2, 3, 4])

print(a1)
print(a1.T)
print(a1 * a1.T)
print(a1.dot(a1.T))
print(np.multiply(a1, a1))

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
[[30]]
[[30]]
[[ 1  4  9 16]]
[1 2 3 4]
[1 2 3 4]
[ 1  4  9 16]
30
[ 1  4  9 16]


In [4]:
s, v, m = 10, [1, 2, 3], np.array([[1, 2, 3], [4, 5, 6]])
print(s, type(s))
print(v, type(v))
print(m, type(m))

(10, <type 'int'>)
([1, 2, 3], <type 'list'>)
(array([[1, 2, 3],
       [4, 5, 6]]), <type 'numpy.ndarray'>)


In [5]:
import math

x = np.array([1, 2])
mag = lambda x: math.sqrt(sum(i ** 2 for i in x))
print(mag(x))
print(np.linalg.norm(x))

2.2360679775
2.2360679775
