In [1]:
import numpy as np

a1 = np.array([1, 2, 3])
a2 = np.array([[1, 2, 3]])
a3 = np.array([[1], [2], [3]])

print(a1)
print(a1.ndim, a1.shape)
print(a2)
print(a2.ndim, a2.shape)
print(a3)
print(a3.ndim, a3.shape)

[1 2 3]
(1, (3,))
[[1 2 3]]
(2, (1, 3))
[[1]
 [2]
 [3]]
(2, (3, 1))


In [3]:
m1 = np.matrix([1, 2, 3, 4])

print(m1)
print(m1.T)
print(m1 * m1.T)
print(m1.dot(m1.T))
print(np.multiply(m1, m1))

a1 = np.array([1, 2, 3, 4])

print(a1)
print(a1.T)
print(a1 * a1.T)
print(a1.dot(a1.T))
print(np.multiply(a1, a1))

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
[[30]]
[[30]]
[[ 1  4  9 16]]
[1 2 3 4]
[1 2 3 4]
[ 1  4  9 16]
30
[ 1  4  9 16]


In [4]:
s, v, m = 10, [1, 2, 3], np.array([[1, 2, 3], [4, 5, 6]])
print(s, type(s))
print(v, type(v))
print(m, type(m))

(10, <type 'int'>)
([1, 2, 3], <type 'list'>)
(array([[1, 2, 3],
       [4, 5, 6]]), <type 'numpy.ndarray'>)


In [5]:
import math

x = np.array([1, 2])
mag = lambda x: math.sqrt(sum(i ** 2 for i in x))
print(mag(x))
print(np.linalg.norm(x))

2.2360679775
2.2360679775


In [2]:
import math

def add(u, v):
    return [u[i] + v[i] for i in range(len(u))]

def magnitude(v):
    return math.sqrt(sum(v[i] * v[i] for i in range(len(v))))

def normalize(v):
    vmag = magnitude(v)
    return [v[i] / vmag for i in range(len(v))]

l, v = [1, 1, 1], [0, 0, 0]
h = normalize(add(l, v))
print(magnitude(add(l, v)))
print(h)

1.73205080757
[0.5773502691896258, 0.5773502691896258, 0.5773502691896258]


In [4]:
import numpy as np
d, e = np.array([4, 5]), np.array([3, 8])
f = d + e
print(f)

[ 7 13]


In [1]:
import math
import numpy as np
d, e = np.array([1, 2]), np.array([2, 1])
g = d - e
print(g)

[-1  1]


In [2]:
d = np.array([1, 2])
i = 3 * d
print(i)

[3 6]


In [3]:
d, e = np.array([4, 5]), np.array([3, 8])
j = d * e
print(j)
print(np.dot(d, e))

[12 40]
52


In [4]:
va, vb, vc = np.array([[1, 0]]), np.array([[4, 1]]), np.array([[4], [1]])
print(np.vdot(va, vb))
print(np.vdot(va, vc))

4
4


In [5]:
d, e = np.array([4, 5]), np.array([3, 8])
print(np.cross(d, e))
d, e = np.array([4, 5, 4]), np.array([3, 8, 2])
print(np.cross(d, e))

17
[-22   4  17]


In [6]:
a, b = np.array([[1, 0]]), np.array([[4, 1]])
print(a.shape, b.shape)
print(np.inner(a, b))
a1, b1 = np.array([[1, 0, 3]]), np.array([[4, 1, 3]])
print(a1.shape, b1.shape)
print(np.inner(a1, b1))

((1, 2), (1, 2))
[[4]]
((1, 3), (1, 3))
[[13]]


In [8]:
va, vb, vc = np.array([[1, 0]]), np.array([[4, 1]]), np.array([[4], [1]])
print(np.dot(va, vc))
print(np.inner(va, vb))

[[4]]
[[4]]
